/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LoginCard: typeof import('./src/components/Login/LoginCard.vue')['default']
    LoginFooter: typeof import('./src/components/Login/LoginFooter.vue')['default']
    LoginForm: typeof import('./src/components/Login/LoginForm.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    Snackbar: typeof import('./src/components/Snackbar.vue')['default']
  }
}
