/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionBtn: typeof import('./src/components/StudentForm/ActionBtn.vue')['default']
    ConfirmationDialog: typeof import('./src/components/ConfirmationDialog.vue')['default']
    LoginCard: typeof import('./src/components/Login/LoginCard.vue')['default']
    LoginFooter: typeof import('./src/components/Login/LoginFooter.vue')['default']
    LoginForm: typeof import('./src/components/Login/LoginForm.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    Snackbar: typeof import('./src/components/Snackbar.vue')['default']
    StudentForm: typeof import('./src/components/StudentForm/StudentForm.vue')['default']
    StudentFormButtons: typeof import('./src/components/StudentForm/StudentFormButtons.vue')['default']
    StudentListHeader: typeof import('./src/components/StudentList/StudentListHeader.vue')['default']
  }
}
