name: CI

on:
  push:
    branches: ['develop, main']
  pull_request:
    branches: ['develop, main']

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Npm install depencias Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          cache: 'npm'

      - run: npm ci
      - name: Linting
        run: npm run lint
      - name: Testing
        run: npm run test

      - name: Testing
        run: npm run build
